import type { GroupConfig } from '../types'

export const groups: GroupConfig[] = [
  {
    id: 'environment',
    displayName: 'Environment',
    icon: 'Thermometer',
    tiles: [
      { deviceId: '68', label: 'Greenhouse Fan', tileType: 'switch' },
      { deviceId: '1320', label: 'Chicken Pen Heater', tileType: 'switch' },
      { deviceId: '66', label: 'Office Fans', tileType: 'switch' },
      { deviceId: '1273', label: 'Office Skeeter', tileType: 'switch' },
      { deviceId: '1284', label: 'Concrete ZR', tileType: 'switch' },
      { deviceId: '223', label: 'Lanai Temp', tileType: 'temperature' },
      { deviceId: '1225', label: 'Greenhouse Motion', tileType: 'temperature' },
      { label: 'Sunrise', tileType: 'hub-variable', hubVarName: 'Sunrise' },
      { label: 'Sunset', tileType: 'hub-variable', hubVarName: 'Sunset' },
    ],
  },
  {
    id: 'security-alarm',
    displayName: 'Security Alarm',
    icon: 'Bell',
    tiles: [
      { tileType: 'hsm', label: 'Security System' },
      { deviceId: '', label: 'Ring Mode On Off', tileType: 'connector' },
    ],
  },
  {
    id: 'night-security',
    displayName: 'Night Security',
    icon: 'Moon',
    tiles: [
      { deviceId: '785', label: 'LR Window 1', tileType: 'contact' },
      { deviceId: '786', label: 'LR Window 2', tileType: 'contact' },
      { deviceId: '787', label: 'LR Window 3', tileType: 'contact' },
      { deviceId: '788', label: 'LR Window 4', tileType: 'contact' },
      { deviceId: '797', label: 'Office Door', tileType: 'contact' },
      { deviceId: '60', label: 'Front Door', tileType: 'contact' },
      { deviceId: '53', label: 'Door Living Room French', tileType: 'contact' },
      { deviceId: '682', label: 'Door Dining Room', tileType: 'contact' },
      { deviceId: '1275', label: 'Door Lanai', tileType: 'contact' },
      { deviceId: '1307', label: 'Door BirdHouse', tileType: 'contact' },
      { deviceId: '1334', label: 'Door BH Screen', tileType: 'contact' },
      { deviceId: '1270', label: 'Woodshed Door', tileType: 'contact' },
      { deviceId: '47', label: 'Flood Woodshed', tileType: 'switch' },
      { deviceId: '113', label: 'Flood Side', tileType: 'switch' },
      { deviceId: '136', label: 'Flood Office Rear', tileType: 'switch' },
      { deviceId: '1161', label: 'Flood Side 2', tileType: 'switch' },
      { deviceId: '220', label: 'Flood Shower', tileType: 'switch' },
      { deviceId: '1228', label: 'Carport Flood', tileType: 'switch' },
    ],
  },
  {
    id: 'lights',
    displayName: 'Lights',
    icon: 'Lightbulb',
    tiles: [
      { deviceId: '1293', label: 'Desk CT', tileType: 'rgbw' },
      { deviceId: '1309', label: 'BirdHouse Outside', tileType: 'rgbw' },
      { deviceId: '1329', label: "Marji's Light", tileType: 'rgbw' },
      { deviceId: '441', label: 'Light Strip', tileType: 'rgbw' },
      { deviceId: '1326', label: 'Lan Strip', tileType: 'rgbw' },
      { deviceId: '335', label: 'Porch Light', tileType: 'rgbw' },
      { deviceId: '1279', label: 'Guest Light', tileType: 'rgbw' },
      { deviceId: '114', label: 'N Guest', tileType: 'switch' },
      { deviceId: '115', label: 'Bedroom Light', tileType: 'switch' },
      { deviceId: '1001', label: 'Porch Dining', tileType: 'switch' },
      { deviceId: '1002', label: 'Lanai Lamp', tileType: 'switch' },
      { deviceId: '1277', label: 'Closet', tileType: 'switch' },
      { deviceId: '1278', label: 'N Guest Light', tileType: 'switch' },
      { deviceId: '1280', label: 'ZB New 1', tileType: 'switch' },
      { deviceId: '792', label: 'L Tree', tileType: 'switch' },
      { deviceId: '207', label: 'Clock Tree', tileType: 'switch' },
      { deviceId: '585', label: 'Lania Tree', tileType: 'switch' },
    ],
  },
  {
    id: 'doors-windows',
    displayName: 'Doors & Windows',
    icon: 'DoorOpen',
    tiles: [
      { deviceId: '60', label: 'Front Door', tileType: 'contact' },
      { deviceId: '53', label: 'Door Living Room French', tileType: 'contact' },
      { deviceId: '682', label: 'Door Dining Room', tileType: 'contact' },
      { deviceId: '1275', label: 'Door Lanai', tileType: 'contact' },
      { deviceId: '797', label: 'Office Door', tileType: 'contact' },
      { deviceId: '1307', label: 'Door BirdHouse', tileType: 'contact' },
      { deviceId: '1334', label: 'Door BH Screen', tileType: 'contact' },
      { deviceId: '1270', label: 'Woodshed Door', tileType: 'contact' },
      { deviceId: '785', label: 'LR Window 1', tileType: 'contact' },
      { deviceId: '786', label: 'LR Window 2', tileType: 'contact' },
      { deviceId: '787', label: 'LR Window 3', tileType: 'contact' },
      { deviceId: '788', label: 'LR Window 4', tileType: 'contact' },
      { deviceId: '1337', label: 'Concrete Shed', tileType: 'contact' },
      { deviceId: '1338', label: 'Safe', tileType: 'contact' },
      { deviceId: '1360', label: 'Freezer Door', tileType: 'contact' },
    ],
  },
  {
    id: 'presence-motion',
    displayName: 'Presence & Motion',
    icon: 'User',
    tiles: [
      { deviceId: '6', label: 'Carport Front Motion', tileType: 'motion' },
      { deviceId: '8', label: 'Carport Rear Motion', tileType: 'motion' },
      { deviceId: '40', label: 'Top Back Door', tileType: 'motion' },
      { deviceId: '271', label: 'Concrete Shed Motion', tileType: 'motion' },
      { deviceId: '437', label: 'Desk Motion', tileType: 'motion' },
      { deviceId: '779', label: 'WoodShed Motion', tileType: 'motion' },
      { deviceId: '809', label: 'Chicken Pen Outside', tileType: 'motion' },
      { deviceId: '1130', label: 'Rear Carport', tileType: 'motion' },
      { deviceId: '1294', label: 'RV Motion', tileType: 'motion' },
      { deviceId: '1362', label: 'Extra Third Motion Sensor', tileType: 'motion' },
      { deviceId: '1371', label: 'Motion At Backdoor', tileType: 'motion' },
      { deviceId: '681', label: 'Dining Motion', tileType: 'motion' },
      { deviceId: '1328', label: 'Shower Motion Temp', tileType: 'motion' },
      { deviceId: '144', label: 'Front Door Ring Motion', tileType: 'switch' },
      { deviceId: '783', label: "Tim's Phone Home", tileType: 'presence' },
      { deviceId: '1306', label: "Tim's Phone Home HD", tileType: 'presence' },
    ],
  },
  {
    id: 'perimeter',
    displayName: 'Perimeter',
    icon: 'Shield',
    tiles: [
      { deviceId: '1193', label: 'Side Yard Gate', tileType: 'contact' },
      { deviceId: '1308', label: 'Front Gate', tileType: 'contact' },
      { deviceId: '1269', label: 'Carport Beam', tileType: 'contact' },
      { deviceId: '1285', label: 'RG Shock', tileType: 'contact' },
      { deviceId: '1257', label: 'RPD Front Door', tileType: 'ring-detection', hubVarName: 'LRPFrontDoor' },
      { deviceId: '1283', label: 'RPD Back Door', tileType: 'ring-detection', hubVarName: 'LRPBackDoor' },
      { deviceId: '1319', label: 'RPD BirdHouse', tileType: 'ring-detection', hubVarName: 'LRPBirdHouse' },
      { deviceId: '1333', label: 'RPD Garden', tileType: 'ring-detection', hubVarName: 'LRPGarden' },
      { deviceId: '1318', label: 'RPD CPen', tileType: 'ring-detection', hubVarName: 'LRPCPen' },
    ],
  },
  {
    id: 'emergency',
    displayName: 'Emergency',
    icon: 'AlertTriangle',
    tiles: [
      { deviceId: '277', label: 'Desk Button', tileType: 'button' },
      { deviceId: '440', label: 'Help Needed VRT', tileType: 'button' },
      { deviceId: '47', label: 'Flood Woodshed', tileType: 'switch' },
      { deviceId: '113', label: 'Flood Side', tileType: 'switch' },
      { deviceId: '136', label: 'Flood Office Rear', tileType: 'switch' },
      { deviceId: '1309', label: 'BirdHouse Outside', tileType: 'rgbw' },
    ],
  },
  {
    id: 'cameras',
    displayName: 'Cameras',
    icon: 'Camera',
    tiles: [
      { deviceId: '802', label: 'LR Cam', tileType: 'switch' },
      { deviceId: '64', label: 'Dining Cam', tileType: 'switch' },
      { deviceId: '67', label: 'GH Alexa', tileType: 'switch' },
      { deviceId: '1291', label: 'RV OUT 1', tileType: 'switch' },
      { deviceId: '1292', label: 'RV OUT 2', tileType: 'switch' },
      { deviceId: '750', label: 'Alexa Office', tileType: 'switch' },
    ],
  },
  {
    id: 'ring-detections',
    displayName: 'Ring Detections',
    icon: 'Bell',
    tiles: [
      { deviceId: '1257', label: 'RPD Front Door', tileType: 'ring-detection', hubVarName: 'LRPFrontDoor' },
      { deviceId: '1283', label: 'RPD Back Door', tileType: 'ring-detection', hubVarName: 'LRPBackDoor' },
      { deviceId: '1319', label: 'RPD BirdHouse', tileType: 'ring-detection', hubVarName: 'LRPBirdHouse' },
      { deviceId: '1333', label: 'RPD Garden', tileType: 'ring-detection', hubVarName: 'LRPGarden' },
      { deviceId: '1318', label: 'RPD CPen', tileType: 'ring-detection', hubVarName: 'LRPCPen' },
      { label: 'Echo Message', tileType: 'hub-variable', hubVarName: 'EchoMessage' },
    ],
  },
  {
    id: 'seasonal',
    displayName: 'Seasonal',
    icon: 'Star',
    tiles: [
      { deviceId: '1282', label: 'Lania Xmas 1', tileType: 'power-meter' },
      { deviceId: '1321', label: 'Court Yard 1', tileType: 'power-meter' },
      { deviceId: '1322', label: 'Living Xmas 1', tileType: 'power-meter' },
      { deviceId: '1323', label: 'Concrete Xmas 1', tileType: 'power-meter' },
      { deviceId: '782', label: 'Living Tree 2', tileType: 'switch' },
      { deviceId: '617', label: 'Yard Xmas 1', tileType: 'switch' },
      { deviceId: '585', label: 'Lania Tree', tileType: 'switch' },
      { deviceId: '1264', label: 'Dining Tree', tileType: 'switch' },
      { deviceId: '1276', label: 'Carport Christmas', tileType: 'switch' },
      { deviceId: '139', label: 'Christmas Fun', tileType: 'switch' },
    ],
  },
  {
    id: 'hub-mode',
    displayName: 'Hub Mode',
    icon: 'Clock',
    tiles: [
      { label: 'Hub Mode', tileType: 'mode' },
      { deviceId: '1133', label: 'Mode Device', tileType: 'switch' },
    ],
  },
  {
    id: 'power-monitor',
    displayName: 'Power Monitor',
    icon: 'Zap',
    tiles: [
      { deviceId: '1343', label: 'On Mains', tileType: 'connector' },
      { deviceId: '1359', label: 'Ignore Mains Check', tileType: 'connector' },
      { deviceId: '1325', label: 'Printer', tileType: 'power-meter' },
    ],
  },
  {
    id: 'system',
    displayName: 'System',
    icon: 'Settings',
    tiles: [
      { label: 'Security System', tileType: 'hsm' },
      { label: 'Hub Mode', tileType: 'mode' },
      { deviceId: '', label: 'Alarm Stop', tileType: 'connector' },
      { deviceId: '', label: 'Alarm Trigger', tileType: 'connector' },
      { deviceId: '486', label: 'Alarms Enabled', tileType: 'connector' },
      { deviceId: '', label: 'All Lights Control', tileType: 'connector' },
      { deviceId: '1377', label: 'AMC Motion Side Yard', tileType: 'connector' },
      { deviceId: '', label: 'Arrive Grace Period Switch', tileType: 'connector' },
      { deviceId: '1324', label: 'Audible Alarms On', tileType: 'connector' },
      { deviceId: '1301', label: 'Carport Siren', tileType: 'connector' },
      { deviceId: '1265', label: 'Christmas Lights', tileType: 'connector' },
      { deviceId: '1313', label: 'Christmas Trees', tileType: 'connector' },
      { deviceId: '1137', label: 'Dog On Floor Off', tileType: 'connector' },
      { deviceId: '1296', label: 'Dogs Fed', tileType: 'connector' },
      { deviceId: '1365', label: 'Dogs Outside', tileType: 'connector' },
      { deviceId: '1340', label: 'DW Status Report', tileType: 'connector' },
      { deviceId: '1341', label: 'DW Status Run Now', tileType: 'connector' },
      { deviceId: '', label: 'Emergency Lights On', tileType: 'connector' },
      { deviceId: '1346', label: 'Flood Office Rear SW', tileType: 'connector' },
      { deviceId: '1227', label: 'High Alert', tileType: 'connector' },
      { deviceId: '1316', label: 'Holiday', tileType: 'connector' },
      { deviceId: '1359', label: 'Ignore Mains Check', tileType: 'connector' },
      { deviceId: '', label: 'Indoor Cams Switch', tileType: 'connector' },
      { deviceId: '969', label: 'Leaving Mode', tileType: 'connector' },
      { deviceId: '', label: 'Night Lights', tileType: 'connector' },
      { deviceId: '1343', label: 'On Mains', tileType: 'connector' },
      { deviceId: '1327', label: 'On PTO', tileType: 'connector' },
      { deviceId: '', label: 'Panic Button', tileType: 'connector' },
      { deviceId: '484', label: 'Pause BD Alarm', tileType: 'connector' },
      { deviceId: '', label: 'Pause Carport Beam', tileType: 'connector' },
      { deviceId: '683', label: 'Pause DR Door Alarm', tileType: 'connector' },
      { deviceId: '1287', label: 'Phone Leaving Disabled', tileType: 'connector' },
      { deviceId: '1354', label: 'Raining Now', tileType: 'connector' },
      { deviceId: '746', label: 'Rear Gate Active', tileType: 'connector' },
      { deviceId: '1314', label: 'Safe Locked', tileType: 'connector' },
      { deviceId: '487', label: 'See Slack', tileType: 'connector' },
      { deviceId: '1295', label: 'Set Away Delay', tileType: 'connector' },
      { deviceId: '1261', label: 'Silence Office', tileType: 'connector' },
      { deviceId: '905', label: 'Silent', tileType: 'connector' },
      { deviceId: '1372', label: 'Silent Backdoor', tileType: 'connector' },
      { deviceId: '1258', label: 'Silent Carport', tileType: 'connector' },
      { deviceId: '1303', label: 'Siren 3-25', tileType: 'connector' },
      { deviceId: '1364', label: 'Skeeters', tileType: 'connector' },
      { deviceId: '798', label: 'Stop Shower Help', tileType: 'connector' },
      { deviceId: '559', label: 'Summer Time', tileType: 'connector' },
      { deviceId: '1298', label: 'Tell Me Active', tileType: 'connector' },
      { deviceId: '783', label: "Tim's Phone Home", tileType: 'connector' },
      { deviceId: '1306', label: "Tim's Phone Home HD", tileType: 'connector' },
      { deviceId: '1268', label: 'Traveling', tileType: 'connector' },
      { deviceId: '1297', label: 'Water Is On', tileType: 'connector' },
    ],
  },
  {
    id: 'other',
    displayName: 'Other',
    icon: 'LayoutGrid',
    tiles: [], // populated dynamically at runtime from unclaimed devices
  },
]
